main.exe:  main.cc paciente.cc funciones.cc historial.cc citas.cc citas_menu.cc historial_menu.cc paciente_menu.cc
	g++ -Wall -o main.exe main.cc paciente.cc funciones.cc historial.cc citas.cc tratamiento.cc citas_menu.cc historial_menu.cc paciente_menu.cc tratamiento_menu.cc -std=gnu++11
